In [1]:
import torch

In [ ]:
# 1. Создайте случайный FloatTensor размера 3x4x5

In [5]:
x = torch.randn(3, 4, 5)
x

tensor([[[-0.1192, -0.2033, -0.0925,  0.0975, -0.3598],
         [-1.1633,  0.4128, -0.1150,  1.3689,  0.1492],
         [-0.8891, -0.9465, -0.3476,  1.1804,  0.6070],
         [-0.0041, -1.1674, -1.1730, -1.2092, -0.6357]],

        [[-0.9143,  0.9681, -1.5015,  0.3508, -0.3861],
         [ 0.4342,  0.6481,  0.6926,  1.7013,  1.6251],
         [ 0.6270, -0.4476, -0.5777, -2.3564,  1.1775],
         [ 0.7533, -0.3332,  0.8863, -1.1731,  0.0465]],

        [[ 0.1074,  0.6810,  1.7710, -1.0140, -2.0275],
         [-1.0616,  0.4528, -0.5298,  0.0089, -0.0892],
         [-0.4547,  0.4957, -0.2965,  0.1500, -1.7896],
         [ 1.5109,  1.5919,  1.8025,  1.4040,  0.5190]]])

In [ ]:
# 2. Выведите его форму (shape)

In [6]:
print('Тензор x: ', x.type(), x.shape)

Тензор x:  torch.FloatTensor torch.Size([3, 4, 5])


In [ ]:
# 3. Приведите его к форме 6х10

In [7]:
x = torch.reshape(x, [6, 10])
x, x.shape

(tensor([[-0.1192, -0.2033, -0.0925,  0.0975, -0.3598, -1.1633,  0.4128, -0.1150,
           1.3689,  0.1492],
         [-0.8891, -0.9465, -0.3476,  1.1804,  0.6070, -0.0041, -1.1674, -1.1730,
          -1.2092, -0.6357],
         [-0.9143,  0.9681, -1.5015,  0.3508, -0.3861,  0.4342,  0.6481,  0.6926,
           1.7013,  1.6251],
         [ 0.6270, -0.4476, -0.5777, -2.3564,  1.1775,  0.7533, -0.3332,  0.8863,
          -1.1731,  0.0465],
         [ 0.1074,  0.6810,  1.7710, -1.0140, -2.0275, -1.0616,  0.4528, -0.5298,
           0.0089, -0.0892],
         [-0.4547,  0.4957, -0.2965,  0.1500, -1.7896,  1.5109,  1.5919,  1.8025,
           1.4040,  0.5190]]), torch.Size([6, 10]))

In [ ]:
# 4. Создайте случайный IntTensor размера 10

In [8]:
y = torch.IntTensor(10)
y, y.type()

(tensor([  97399104,          0,         27,          0,         -1,   16843009,
          678913390, 1142959146, 1667855973, 1679834981], dtype=torch.int32),
 'torch.IntTensor')

In [ ]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [9]:
x*y

tensor([[-1.1605e+07, -0.0000e+00, -2.4967e+00,  0.0000e+00,  3.5981e-01,
         -1.9593e+07,  2.8027e+08, -1.3149e+08,  2.2832e+09,  2.5066e+08],
        [-8.6595e+07, -0.0000e+00, -9.3841e+00,  0.0000e+00, -6.0705e-01,
         -6.8355e+04, -7.9258e+08, -1.3407e+09, -2.0168e+09, -1.0679e+09],
        [-8.9053e+07,  0.0000e+00, -4.0540e+01,  0.0000e+00,  3.8609e-01,
          7.3135e+06,  4.4003e+08,  7.9156e+08,  2.8375e+09,  2.7298e+09],
        [ 6.1070e+07, -0.0000e+00, -1.5597e+01, -0.0000e+00, -1.1775e+00,
          1.2687e+07, -2.2625e+08,  1.0130e+09, -1.9566e+09,  7.8058e+07],
        [ 1.0457e+07,  0.0000e+00,  4.7818e+01, -0.0000e+00,  2.0275e+00,
         -1.7880e+07,  3.0743e+08, -6.0551e+08,  1.4803e+07, -1.4990e+08],
        [-4.4291e+07,  0.0000e+00, -8.0051e+00,  0.0000e+00,  1.7896e+00,
          2.5448e+07,  1.0808e+09,  2.0601e+09,  2.3417e+09,  8.7180e+08]])

In [ ]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти

In [11]:
x @ x.T

tensor([[ 3.6361, -1.8653,  2.4783, -3.2985,  1.7973,  1.3311],
        [-1.8653,  8.1740, -4.0630, -1.2642, -3.6401, -6.8777],
        [ 2.4783, -4.0630, 10.9234, -2.6159, -2.3352,  8.2526],
        [-3.2985, -1.2642, -2.6159, 10.7086, -2.6934, -2.2144],
        [ 1.7973, -3.6401, -2.3352, -2.6934, 10.3716,  1.3683],
        [ 1.3311, -6.8777,  8.2526, -2.2144,  1.3683, 14.0720]])

In [12]:
torch.matmul(x, x.T)

tensor([[ 3.6361, -1.8653,  2.4783, -3.2985,  1.7973,  1.3311],
        [-1.8653,  8.1740, -4.0630, -1.2642, -3.6401, -6.8777],
        [ 2.4783, -4.0630, 10.9234, -2.6159, -2.3352,  8.2526],
        [-3.2985, -1.2642, -2.6159, 10.7086, -2.6934, -2.2144],
        [ 1.7973, -3.6401, -2.3352, -2.6934, 10.3716,  1.3683],
        [ 1.3311, -6.8777,  8.2526, -2.2144,  1.3683, 14.0720]])

In [ ]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [14]:
x = torch.autograd.Variable(torch.FloatTensor([1]),   requires_grad = True)
z = torch.autograd.Variable(torch.FloatTensor([0.5]), requires_grad = True)
t = torch.autograd.Variable(torch.FloatTensor([2]),   requires_grad = True)

y = x**3 + z -75*t

y.backward()

(x.grad, z.grad, t.grad)

(tensor([3.]), tensor([1.]), tensor([-75.]))

In [ ]:
# 8. Создайте единичный тензор размера 5x6

In [15]:
one_t = torch.ones([5, 6])
one_t, one_t.shape

(tensor([[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]), torch.Size([5, 6]))

In [ ]:
# 9. Переведите его в формат numpy

In [16]:
one_t_n = one_t.numpy()
one_t_n

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)